# Generated by Django 3.0.5 on 2020-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ManyToManyField(related_name='tables', to='booking.Table'),
        ),
    ]
