# Generated by Django 3.0.5 on 2020-04-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200427_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_email',
            field=models.CharField(max_length=255),
        ),
    ]
